# Generated by Django 2.2.3 on 2022-07-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20220702_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Nombre',
            field=models.CharField(default='exit', max_length=20, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
