# Generated by Django 2.2.3 on 2022-07-03 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
