# Generated by Django 2.2.3 on 2022-07-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20220702_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ProductoId',
        ),
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.AutoField(auto_created=True, default='exit', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
