# Generated by Django 2.2.3 on 2022-07-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_auto_20220702_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='ProductoId',
            field=models.IntegerField(default='exit', primary_key=True, serialize=False, verbose_name='ProductoId'),
            preserve_default=False,
        ),
    ]
