# Generated by Django 2.2.3 on 2022-07-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_auto_20220702_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Stock',
            field=models.FloatField(verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Valor',
            field=models.FloatField(verbose_name='Valor'),
        ),
    ]
