# Generated by Django 2.2.3 on 2022-07-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_auto_20220702_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Stock',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Valor',
            field=models.FloatField(),
        ),
    ]
